server:
  port: 8080  # ← 포트 번호 추가

spring:
  application:
    name: library
  web:
    cors:
      allowed-origins: "http://localhost:5173"  # ← CORS 설정 추가
      allowed-methods: "*"
      allowed-headers: "*"

openai:
  api:
    key:

